name: Publish

on:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-lib:
    uses: ./.github/workflows/build.yml
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
  deploy:
    needs: [build-lib]
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-build
          path: packages
          
      - name: install lerna
        run: npm install --global lerna
        shell: bash

      - name: Publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          lerna publish from-package --no-private --yes
